databases:
  - name: mini_project_development
    databaseName: mini_project_development
    user: morty
    plan: free

services:
  - type: web
    name: mini_project_development
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mini_project_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
